services:
  db-ewallet:
    image: postgres:16
    environment:
      - POSTGRES_DB=ewallet-db
      - POSTGRES_USER=ewallet
      - POSTGRES_PASSWORD=ewallet123
    ports:
      - 5432:5432
    volumes:
      - ./db-ewallet:/var/lib/postgresql/data